/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsSlugIndexRouteImport } from './routes/projects.$slug.index'
import { Route as ProjectsSlugChangelogRouteImport } from './routes/projects.$slug.changelog'
import { Route as ProjectsSlugCoverageRouteImport } from './routes/projects.$slug.coverage'
import { Route as ProjectsSlugDiagramsRouteImport } from './routes/projects.$slug.diagrams'
import { Route as ProjectsSlugDocsRouteImport } from './routes/projects.$slug.docs'
import { Route as ProjectsSlugDiagramsIndexRouteImport } from './routes/projects.$slug.diagrams.index'
import { Route as ProjectsSlugDiagramsDiagramIdRouteImport } from './routes/projects.$slug.diagrams.$diagramId'
import { Route as ProjectsSlugDocsIndexRouteImport } from './routes/projects.$slug.docs.index'
import { Route as ProjectsSlugDocsPageIdRouteImport } from './routes/projects.$slug.docs.$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugIndexRoute = ProjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugChangelogRoute = ProjectsSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugCoverageRoute = ProjectsSlugCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugDiagramsRoute = ProjectsSlugDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugDocsRoute = ProjectsSlugDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugDiagramsIndexRoute =
  ProjectsSlugDiagramsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsSlugDiagramsRoute,
  } as any)
const ProjectsSlugDiagramsDiagramIdRoute =
  ProjectsSlugDiagramsDiagramIdRouteImport.update({
    id: '/$diagramId',
    path: '/$diagramId',
    getParentRoute: () => ProjectsSlugDiagramsRoute,
  } as any)
const ProjectsSlugDocsIndexRoute = ProjectsSlugDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugDocsRoute,
} as any)
const ProjectsSlugDocsPageIdRoute = ProjectsSlugDocsPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => ProjectsSlugDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/changelog': typeof ProjectsSlugChangelogRoute
  '/projects/$slug/coverage': typeof ProjectsSlugCoverageRoute
  '/projects/$slug/diagrams': typeof ProjectsSlugDiagramsRouteWithChildren
  '/projects/$slug/docs': typeof ProjectsSlugDocsRouteWithChildren
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
  '/projects/$slug/diagrams/$diagramId': typeof ProjectsSlugDiagramsDiagramIdRoute
  '/projects/$slug/docs/$pageId': typeof ProjectsSlugDocsPageIdRoute
  '/projects/$slug/diagrams/': typeof ProjectsSlugDiagramsIndexRoute
  '/projects/$slug/docs/': typeof ProjectsSlugDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/projects/$slug/changelog': typeof ProjectsSlugChangelogRoute
  '/projects/$slug/coverage': typeof ProjectsSlugCoverageRoute
  '/projects/$slug': typeof ProjectsSlugIndexRoute
  '/projects/$slug/diagrams/$diagramId': typeof ProjectsSlugDiagramsDiagramIdRoute
  '/projects/$slug/docs/$pageId': typeof ProjectsSlugDocsPageIdRoute
  '/projects/$slug/diagrams': typeof ProjectsSlugDiagramsIndexRoute
  '/projects/$slug/docs': typeof ProjectsSlugDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/changelog': typeof ProjectsSlugChangelogRoute
  '/projects/$slug/coverage': typeof ProjectsSlugCoverageRoute
  '/projects/$slug/diagrams': typeof ProjectsSlugDiagramsRouteWithChildren
  '/projects/$slug/docs': typeof ProjectsSlugDocsRouteWithChildren
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
  '/projects/$slug/diagrams/$diagramId': typeof ProjectsSlugDiagramsDiagramIdRoute
  '/projects/$slug/docs/$pageId': typeof ProjectsSlugDocsPageIdRoute
  '/projects/$slug/diagrams/': typeof ProjectsSlugDiagramsIndexRoute
  '/projects/$slug/docs/': typeof ProjectsSlugDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/projects/$slug'
    | '/projects/$slug/changelog'
    | '/projects/$slug/coverage'
    | '/projects/$slug/diagrams'
    | '/projects/$slug/docs'
    | '/projects/$slug/'
    | '/projects/$slug/diagrams/$diagramId'
    | '/projects/$slug/docs/$pageId'
    | '/projects/$slug/diagrams/'
    | '/projects/$slug/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/projects/$slug/changelog'
    | '/projects/$slug/coverage'
    | '/projects/$slug'
    | '/projects/$slug/diagrams/$diagramId'
    | '/projects/$slug/docs/$pageId'
    | '/projects/$slug/diagrams'
    | '/projects/$slug/docs'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/experience'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/projects/$slug'
    | '/projects/$slug/changelog'
    | '/projects/$slug/coverage'
    | '/projects/$slug/diagrams'
    | '/projects/$slug/docs'
    | '/projects/$slug/'
    | '/projects/$slug/diagrams/$diagramId'
    | '/projects/$slug/docs/$pageId'
    | '/projects/$slug/diagrams/'
    | '/projects/$slug/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug/': {
      id: '/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof ProjectsSlugIndexRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/changelog': {
      id: '/projects/$slug/changelog'
      path: '/changelog'
      fullPath: '/projects/$slug/changelog'
      preLoaderRoute: typeof ProjectsSlugChangelogRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/coverage': {
      id: '/projects/$slug/coverage'
      path: '/coverage'
      fullPath: '/projects/$slug/coverage'
      preLoaderRoute: typeof ProjectsSlugCoverageRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/diagrams': {
      id: '/projects/$slug/diagrams'
      path: '/diagrams'
      fullPath: '/projects/$slug/diagrams'
      preLoaderRoute: typeof ProjectsSlugDiagramsRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/docs': {
      id: '/projects/$slug/docs'
      path: '/docs'
      fullPath: '/projects/$slug/docs'
      preLoaderRoute: typeof ProjectsSlugDocsRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/diagrams/': {
      id: '/projects/$slug/diagrams/'
      path: '/'
      fullPath: '/projects/$slug/diagrams/'
      preLoaderRoute: typeof ProjectsSlugDiagramsIndexRouteImport
      parentRoute: typeof ProjectsSlugDiagramsRoute
    }
    '/projects/$slug/diagrams/$diagramId': {
      id: '/projects/$slug/diagrams/$diagramId'
      path: '/$diagramId'
      fullPath: '/projects/$slug/diagrams/$diagramId'
      preLoaderRoute: typeof ProjectsSlugDiagramsDiagramIdRouteImport
      parentRoute: typeof ProjectsSlugDiagramsRoute
    }
    '/projects/$slug/docs/': {
      id: '/projects/$slug/docs/'
      path: '/'
      fullPath: '/projects/$slug/docs/'
      preLoaderRoute: typeof ProjectsSlugDocsIndexRouteImport
      parentRoute: typeof ProjectsSlugDocsRoute
    }
    '/projects/$slug/docs/$pageId': {
      id: '/projects/$slug/docs/$pageId'
      path: '/$pageId'
      fullPath: '/projects/$slug/docs/$pageId'
      preLoaderRoute: typeof ProjectsSlugDocsPageIdRouteImport
      parentRoute: typeof ProjectsSlugDocsRoute
    }
  }
}

interface ProjectsSlugDiagramsRouteChildren {
  ProjectsSlugDiagramsDiagramIdRoute: typeof ProjectsSlugDiagramsDiagramIdRoute
  ProjectsSlugDiagramsIndexRoute: typeof ProjectsSlugDiagramsIndexRoute
}

const ProjectsSlugDiagramsRouteChildren: ProjectsSlugDiagramsRouteChildren = {
  ProjectsSlugDiagramsDiagramIdRoute: ProjectsSlugDiagramsDiagramIdRoute,
  ProjectsSlugDiagramsIndexRoute: ProjectsSlugDiagramsIndexRoute,
}

const ProjectsSlugDiagramsRouteWithChildren =
  ProjectsSlugDiagramsRoute._addFileChildren(ProjectsSlugDiagramsRouteChildren)

interface ProjectsSlugDocsRouteChildren {
  ProjectsSlugDocsPageIdRoute: typeof ProjectsSlugDocsPageIdRoute
  ProjectsSlugDocsIndexRoute: typeof ProjectsSlugDocsIndexRoute
}

const ProjectsSlugDocsRouteChildren: ProjectsSlugDocsRouteChildren = {
  ProjectsSlugDocsPageIdRoute: ProjectsSlugDocsPageIdRoute,
  ProjectsSlugDocsIndexRoute: ProjectsSlugDocsIndexRoute,
}

const ProjectsSlugDocsRouteWithChildren =
  ProjectsSlugDocsRoute._addFileChildren(ProjectsSlugDocsRouteChildren)

interface ProjectsSlugRouteChildren {
  ProjectsSlugChangelogRoute: typeof ProjectsSlugChangelogRoute
  ProjectsSlugCoverageRoute: typeof ProjectsSlugCoverageRoute
  ProjectsSlugDiagramsRoute: typeof ProjectsSlugDiagramsRouteWithChildren
  ProjectsSlugDocsRoute: typeof ProjectsSlugDocsRouteWithChildren
  ProjectsSlugIndexRoute: typeof ProjectsSlugIndexRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugChangelogRoute: ProjectsSlugChangelogRoute,
  ProjectsSlugCoverageRoute: ProjectsSlugCoverageRoute,
  ProjectsSlugDiagramsRoute: ProjectsSlugDiagramsRouteWithChildren,
  ProjectsSlugDocsRoute: ProjectsSlugDocsRouteWithChildren,
  ProjectsSlugIndexRoute: ProjectsSlugIndexRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
